[package]
name = "aoc_2024"
version = "0.1.0"
edition = "2021"

# [lib]
# name = "aoc_2024"
# path = "src/lib.rs"

[profile.release]
debug = true        # keep DWARF info
split-debuginfo = 'unpacked'  # optional, keeps symbols readable
