[package]
name = "aoc_2024"
version = "0.1.0"
edition = "2021"

[profile.release]
incremental = true
debug = 1
strip = false
lto = "fat"
split-debuginfo = "unpacked"

[dependencies]
regex = "1.12.2"

[profile.dev]
debug = true
opt-level = 0
